export const AUTHORS: Record<string, { image: string }> = {
    "Paul Kuper": { image: "/authors/paul.png" },
    "폴 쿠퍼": { image: "/authors/paul.png" },
    "황지원": { image: "/authors/jiwon.png" },
    "Hwang Jiwon": { image: "/authors/jiwon.png" },
    "임지은": { image: "/authors/jieun.png" },
    "Lim Ji-eun": { image: "/authors/jieun.png" },
    "공태준": { image: "/authors/taejun.png" },
    "Kong Tae-jun": { image: "/authors/taejun.png" },
    "Jo Gwi-hyun": { image: "/authors/gwihyun.png" },
    "조귀현": { image: "/authors/gwihyun.png" },
    "Kim Jeong-uk": { image: "/authors/jeonguk.png" },
    "김정욱": { image: "/authors/jeonguk.png" },
    "Jeon Chan-yong": { image: "/authors/chanyong.png" },
    "전찬용": { image: "/authors/chanyong.png" },
    "Jae Lee": { image: "/authors/jae.png" },
    "이경재": { image: "/authors/jae.png" },
    "Kwon Min-jae": { image: "/authors/minjae.png" },
    "권민재": { image: "/authors/minjae.png" },
    "Kim Hee-jun": { image: "/authors/heejun.png" },
    "김희준": { image: "/authors/heejun.png" },
    "Kim Hyun-woo": { image: "/authors/hyunwoo.png" },
    "김현우": { image: "/authors/hyunwoo.png" },
    "Lim Jeong-su": { image: "/authors/jeongsu.png" },
    "임정수": { image: "/authors/jeongsu.png" },

  };